velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  credentials:
    useSecret: true
    existingSecret: velero-secret
  configuration:
    backupStorageLocation:
    - bucket: 03-aws-upstream-velero-bucket
      provider: aws
    volumeSnapshotLocation:
    - config:
        region: eu-central-1
      provider: aws
  # global:
  #   namespace: "default"
