apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/maxxam123/gitops.git
      revision: HEAD
      directories:
      - path: 04_git/aws/01_vpc/01_aws_vpc/01_bootstrap/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/maxxam123/gitops.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: https://F59DA39C94ECD6635A9A7319F27F2708.gr7.eu-central-1.eks.amazonaws.com
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitor
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/maxxam123/gitops.git
      revision: HEAD
      directories:
      - path: 04_git/aws/01_vpc/01_aws_vpc/02_monitor/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/maxxam123/gitops.git
        targetRevision: HEAD
        path: '{{.path}}'
      destination:
        server: https://F59DA39C94ECD6635A9A7319F27F2708.gr7.eu-central-1.eks.amazonaws.com
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
