
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://F59DA39C94ECD6635A9A7319F27F2708.gr7.eu-central-1.eks.amazonaws.com:443
  project: default
  source:
    path: 04_git/aws/01_vpc/01_aps_vpc/01_bootstrap/02_certmanager
    repoURL: https://github.com/maxxam123/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
