---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-03-aws-eks
  # namespace: argocd
  namespace: default  
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: 04_git/aws/10_eks/03_aws_eks/01_bootstrap/nginx/charts/ingress-nginx
    repoURL: 'https://github.com/maxxam123/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
