apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-remote-cluster-02-aws-vpc
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://82C736ADAF4D9BE578746D23825B87FF.gr7.eu-central-1.eks.amazonaws.com
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.6.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
