apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: test
    server: https://kubernetes.default.svc
    name: in-cluster
