apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: 'v1.3.1'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: test01
#   namespace: argocd
# spec:
#   description: Example Project
  
#   sourceRepos:
#   - '*'
  
#   destinations:
#   - namespace: test
#     server: https://kubernetes.default.svc
#     name: in-cluster
