apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test01
  namespace: argocd
spec:
  description: Example Project
  
  sourceRepos:
  - '*'
  
  destinations:
  - namespace: test
    server: https://kubernetes.default.svc
    name: in-cluster
